// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toqlztymptubsjueixve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcWx6dHltcHR1YnNqdWVpeHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTg1MDgsImV4cCI6MjA2NzI3NDUwOH0.3J_BRpCoX3rg5e3xxahp7mlbSxcaLEhMeVLLroDyu90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});